import {
  Server, Users, BarChart3, Globe, CreditCard, Cloud,
  Bot, Layers, Shield, Cpu, Share2, Building2, Briefcase,
  Rocket, Network, TrendingUp
} from "lucide-react";

export const solutions = [
  {
    slug: "forex-broker-infrastructure",
    icon: Server,
    title: "Forex Broker Infrastructure",
    shortDesc: "Complete end-to-end broker setup with trading servers, back-office, and platform integration.",
    description: "Launch or upgrade your forex brokerage with our complete infrastructure stack. From trading server configuration to back-office systems, we handle every layer of your broker technology.",
    features: [
      "MT4/MT5 server setup, configuration & optimization",
      "Liquidity bridge integration with tier-1 providers",
      "Back-office system with full reporting suite",
      "Risk engine & exposure management tools",
      "24/7 infrastructure monitoring & support",
      "Regulatory-ready compliance framework",
    ],
    benefits: [
      { title: "Launch in 14 Days", desc: "Pre-configured broker packages ready to deploy" },
      { title: "99.9% Uptime SLA", desc: "Enterprise-grade reliability for your trading operations" },
      { title: "Scalable Architecture", desc: "Handle from 100 to 100,000+ concurrent traders" },
      { title: "Full White-Glove Setup", desc: "Our team handles every technical detail for you" },
    ],
    color: "from-blue-600 to-blue-400",
    category: "Core Infrastructure",
  },
  {
    slug: "prop-firm-technology",
    icon: TrendingUp,
    title: "Prop Firm Technology",
    shortDesc: "Full-stack prop trading firm platform with challenge engine, evaluation system, and trader management.",
    description: "Build and scale a proprietary trading firm with our purpose-built technology. Challenge systems, evaluation engines, payout management, and trader dashboards — all in one platform.",
    features: [
      "Multi-phase challenge & evaluation engine",
      "Automated trader dashboard with live metrics",
      "Drawdown monitoring & rule enforcement",
      "Funded account provisioning & management",
      "Payout processing & profit-split automation",
      "Affiliate & referral tracking system",
    ],
    benefits: [
      { title: "Custom Challenge Rules", desc: "Design any evaluation structure you want" },
      { title: "Automated Operations", desc: "Run thousands of traders with minimal staff" },
      { title: "Real-Time Monitoring", desc: "Live dashboards for all trader activity" },
      { title: "Rapid Deployment", desc: "Go live in as little as 7 days" },
    ],
    color: "from-violet-600 to-blue-500",
    category: "Prop Trading",
  },
  {
  slug: "ai-trading-robot",
  title: "AI Trading Robot",
  category: "Core Infrastructure",
  shortDesc: "Intelligent automated trading systems powered by AI — execute strategies, manage risk, and optimize performance 24/7.",
  color: "from-violet-600 to-purple-500",
  features: [
    "AI-powered strategy execution engine",
    "Real-time market analysis & signals",
    "Automated risk management rules",
    "Multi-asset trading support",
    "Backtesting & performance analytics",
    "MT4/MT5 bridge integration",
    "Custom algorithm deployment",
    "24/7 automated monitoring",
  ],
},
  {
    slug: "trading-crm-systems",
    icon: Users,
    title: "Trading CRM Systems",
    shortDesc: "Purpose-built forex CRM to manage clients, IBs, leads, and compliance in one platform.",
    description: "A CRM built specifically for forex brokers and prop firms. Manage your entire client lifecycle — from lead capture to onboarding, trading, and retention — with deep trading platform integration.",
    features: [
      "Full client onboarding with KYC/AML workflow",
      "Lead pipeline management & conversion tracking",
      "IB & affiliate management with commission tracking",
      "Integrated with MT4/MT5, cTrader & more",
      "Automated email & notification workflows",
      "Compliance reporting & audit trail",
    ],
    benefits: [
      { title: "One Dashboard", desc: "All client data and trading activity in one place" },
      { title: "Automated Compliance", desc: "KYC/AML checks without manual work" },
      { title: "Higher Conversion", desc: "Smart lead nurturing tools built for forex" },
      { title: "Deep Integration", desc: "Real-time sync with your trading platform" },
    ],
    color: "from-cyan-600 to-blue-500",
    category: "Client Management",
  },
  {
    slug: "trader-ib-portals",
    icon: BarChart3,
    title: "Trader & IB Portals",
    shortDesc: "Branded client portals for traders and introducing brokers with live account data and self-service tools.",
    description: "Give your clients and IBs a world-class portal experience. Branded, responsive, and packed with features — from live account stats to document uploads, funding, and referral tracking.",
    features: [
      "Live trading account dashboard with P&L charts",
      "One-click deposit & withdrawal via integrated PSPs",
      "Document upload & KYC status tracking",
      "IB commission dashboard with real-time reporting",
      "Multi-account management under one login",
      "Mobile-responsive PWA design",
    ],
    benefits: [
      { title: "Fully Branded", desc: "Your logo, colors, and domain — completely white-label" },
      { title: "Self-Service Tools", desc: "Reduce support tickets with client self-service" },
      { title: "IB Growth Engine", desc: "Give IBs visibility to grow their books" },
      { title: "Mobile First", desc: "Optimized for all devices out of the box" },
    ],
    color: "from-teal-600 to-cyan-500",
    category: "Client Portals",
  },
  {
    slug: "payment-gateway-integration",
    icon: CreditCard,
    title: "Payment Gateway Integration",
    shortDesc: "Multi-PSP payment infrastructure with global coverage, crypto support, and real-time reconciliation.",
    description: "Accept deposits and process withdrawals globally with our multi-PSP payment infrastructure. Cards, crypto, bank wire, e-wallets — all integrated, reconciled, and managed from one system.",
    features: [
      "50+ PSP integrations including crypto & e-wallets",
      "Intelligent payment routing for maximum success rates",
      "Automated reconciliation & reporting",
      "Fraud detection & chargeback management",
      "Multi-currency settlement support",
      "PCI-DSS compliant infrastructure",
    ],
    benefits: [
      { title: "Global Coverage", desc: "Accept payments from 150+ countries" },
      { title: "Higher Success Rates", desc: "Smart routing reduces declines automatically" },
      { title: "Crypto Ready", desc: "BTC, ETH, USDT and 20+ cryptocurrencies" },
      { title: "Automated Reconciliation", desc: "Zero manual effort on payment matching" },
    ],
    color: "from-green-600 to-teal-500",
    category: "Payments",
  },
  {
    slug: "vps-cloud-infrastructure",
    icon: Cloud,
    title: "VPS & Cloud Infrastructure",
    shortDesc: "Low-latency trading VPS and cloud hosting optimized for forex platforms and trading algorithms.",
    description: "High-performance VPS and cloud infrastructure designed for forex. Ultra-low latency colocation near major liquidity providers, with managed hosting for MT4/MT5, APIs, and trading bots.",
    features: [
      "Ultra-low latency VPS near LD4, NY4, TY3 data centers",
      "Managed MT4/MT5 server hosting",
      "Auto-scaling cloud for peak load handling",
      "DDoS protection & firewall management",
      "Daily backups with point-in-time recovery",
      "24/7 NOC monitoring & incident response",
    ],
    benefits: [
      { title: "Sub-1ms Latency", desc: "Colocation near top liquidity provider hubs" },
      { title: "Fully Managed", desc: "We handle all infrastructure operations" },
      { title: "Instant Scale", desc: "Scale up resources in minutes, not days" },
      { title: "99.99% Availability", desc: "Enterprise SLA with redundant systems" },
    ],
    color: "from-blue-600 to-blue-500",
    category: "Infrastructure",
  },
  {
    slug: "ai-automation-systems",
    icon: Bot,
    title: "AI Automation Systems",
    shortDesc: "AI-driven automation for trading operations, client communication, risk alerts, and business intelligence.",
    description: "Transform your trading business with AI-powered automation. From intelligent client onboarding to real-time risk alerts and automated reporting, reduce manual work and make data-driven decisions.",
    features: [
      "AI-powered client onboarding & KYC verification",
      "Automated risk monitoring with intelligent alerts",
      "Predictive churn analysis & retention triggers",
      "Natural language reporting via AI assistant",
      "Trading pattern analysis & anomaly detection",
      "Automated compliance report generation",
    ],
    benefits: [
      { title: "80% Less Manual Work", desc: "Automate repetitive operational tasks" },
      { title: "Smarter Risk Management", desc: "AI detects unusual patterns before they escalate" },
      { title: "Better Retention", desc: "Predict and prevent client churn automatically" },
      { title: "Data-Driven Decisions", desc: "AI insights across all your business data" },
    ],
    color: "from-purple-600 to-violet-500",
    category: "AI & Automation",
  },
  {
    slug: "white-label-trading",
    icon: Layers,
    title: "White-Label Trading Solutions",
    shortDesc: "Fully branded white-label trading platforms and broker packages ready to launch under your brand.",
    description: "Launch your own branded trading platform without building from scratch. Our white-label solutions include trading platform, CRM, client portal, and back-office — all under your brand.",
    features: [
      "Fully branded MT4/MT5 or custom trading platform",
      "White-label CRM & back-office system",
      "Branded client and IB portals",
      "Custom domain, logo, and color scheme",
      "Integrated payment processing",
      "Ongoing technical support & updates",
    ],
    benefits: [
      { title: "Launch in 2 Weeks", desc: "Pre-built systems customized to your brand" },
      { title: "Own Your Brand", desc: "Complete white-label with no visible vendor" },
      { title: "Full Stack", desc: "Everything from trading to back-office in one" },
      { title: "Low Cost Entry", desc: "Fraction of the cost of building from scratch" },
    ],
    color: "from-blue-600 to-blue-500",
    category: "White Label",
  },
  {
    slug: "risk-management-systems",
    icon: Shield,
    title: "Risk Management Systems",
    shortDesc: "Real-time risk engine with exposure monitoring, hedging tools, and automated risk controls for brokers.",
    description: "Protect your brokerage from market and operational risk with our enterprise risk management system. Real-time exposure monitoring, automated hedging triggers, and customizable risk rules.",
    features: [
      "Real-time position & exposure monitoring",
      "Automated A/B book management",
      "Customizable risk rules & triggers",
      "Hedging management with liquidity providers",
      "Margin call & stop-out automation",
      "Risk analytics & reporting dashboard",
    ],
    benefits: [
      { title: "Real-Time Control", desc: "Monitor all positions and exposure live" },
      { title: "Automated Safety Nets", desc: "Rules fire automatically without manual action" },
      { title: "A/B Book Management", desc: "Intelligent order routing to optimize risk" },
      { title: "Full Audit Trail", desc: "Every risk decision logged and auditable" },
    ],
    color: "from-red-600 to-orange-500",
    category: "Risk",
  },
  {
    slug: "trading-platform-integration",
    icon: Cpu,
    title: "Trading Platform Integration",
    shortDesc: "Expert integration services for MT4, MT5, cTrader, and custom trading platforms into your ecosystem.",
    description: "Seamlessly integrate any trading platform into your existing or new technology stack. MT4, MT5, cTrader, or custom platforms — connected to your CRM, PSPs, risk engine, and back-office.",
    features: [
      "MT4 & MT5 full integration & configuration",
      "cTrader server setup & customization",
      "Custom API bridge development",
      "Liquidity provider connectivity",
      "Symbol & pricing configuration",
      "Third-party tool & EA integration",
    ],
    benefits: [
      { title: "Any Platform", desc: "MT4, MT5, cTrader, or proprietary — we integrate it" },
      { title: "Expert Team", desc: "Certified platform integration specialists" },
      { title: "Custom Bridges", desc: "Bespoke bridges for unique requirements" },
      { title: "End-to-End", desc: "From setup to go-live with full support" },
    ],
    color: "from-orange-600 to-amber-500",
    category: "Integration",
  },
  {
    slug: "affiliate-referral-systems",
    icon: Share2,
    title: "Affiliate & Referral Systems",
    shortDesc: "Multi-tier affiliate management platform with automated commission tracking, reporting, and payouts.",
    description: "Scale your client acquisition with a powerful affiliate and referral system. Multi-tier commission structures, automated tracking, real-time reporting, and one-click payouts.",
    features: [
      "Multi-tier IB & affiliate program management",
      "Custom commission structures (CPA, RevShare, hybrid)",
      "Automated tracking with unique referral links",
      "Real-time affiliate dashboard & reporting",
      "Automated commission calculation & payout",
      "Marketing material management & delivery",
    ],
    benefits: [
      { title: "Grow Organically", desc: "Turn your clients into your sales force" },
      { title: "Any Commission Model", desc: "CPA, RevShare, hybrid — configure as needed" },
      { title: "Zero Manual Calculation", desc: "Fully automated commission processing" },
      { title: "Transparent Reporting", desc: "Affiliates see their earnings in real time" },
    ],
    color: "from-pink-600 to-rose-500",
    category: "Growth",
  },
];

export const industries = [
  {
    slug: "forex-brokers",
    icon: Globe,
    title: "Forex Brokers",
    shortDesc: "End-to-end technology stack for regulated and offshore forex brokers of all sizes.",
    description: "From startup brokers to established multi-jurisdiction operations, CYTAKE delivers the complete technology infrastructure to run a professional, compliant, and scalable forex brokerage.",
    solutions: ["forex-broker-infrastructure", "trading-crm-systems", "trader-ib-portals", "risk-management-systems", "payment-gateway-integration"],
    color: "from-blue-600 to-blue-400",
  },
  {
    slug: "prop-firms",
    icon: TrendingUp,
    title: "Proprietary Trading Firms",
    shortDesc: "Full-stack prop firm technology including challenge engine, evaluation systems, and funded account management.",
    description: "Launch and scale a prop trading firm with technology built specifically for the industry. Evaluation challenges, risk monitoring, payout automation, and trader management at scale.",
    solutions: ["prop-firm-technology", "trading-crm-systems", "risk-management-systems", "affiliate-referral-systems"],
    color: "from-violet-600 to-blue-500",
  },
  {
    slug: "fintech-startups",
    icon: Rocket,
    title: "Fintech Startups",
    shortDesc: "Modular fintech infrastructure components to build and launch financial technology products rapidly.",
    description: "Get to market faster with pre-built fintech infrastructure. Payment gateways, KYC pipelines, trading connectivity, and cloud infrastructure — available as modular components for your product.",
    solutions: ["payment-gateway-integration", "ai-automation-systems", "vps-cloud-infrastructure", "trading-platform-integration"],
    color: "from-cyan-600 to-blue-500",
  },
  {
    slug: "trading-businesses",
    icon: Building2,
    title: "Trading Businesses",
    shortDesc: "Technology solutions for trading companies, fund managers, and financial services firms.",
    description: "Whether you manage a trading fund, run a financial services business, or operate a trading education platform, CYTAKE's infrastructure adapts to your specific operational requirements.",
    solutions: ["vps-cloud-infrastructure", "ai-automation-systems", "risk-management-systems", "trading-platform-integration"],
    color: "from-green-600 to-teal-500",
  },
  {
    slug: "saas-platforms",
    icon: Network,
    title: "SaaS Platforms",
    shortDesc: "White-label and API-first infrastructure for SaaS companies building in the trading and fintech space.",
    description: "Build fintech SaaS products on top of our robust API infrastructure. White-label components, payment processing, compliance tooling, and scalable cloud — everything you need to build and grow.",
    solutions: ["white-label-trading", "affiliate-referral-systems", "payment-gateway-integration", "ai-automation-systems"],
    color: "from-blue-600 to-purple-500",
  },
];

export const stats = [
  { value: "200+", label: "Brokers Powered", suffix: "" },
  { value: "50+", label: "Countries Served", suffix: "" },
  { value: "99.9", label: "Uptime SLA", suffix: "%" },
  { value: "5", label: "Volume Processed", suffix: "B+" },
  { value: "7", label: "Years of Excellence", suffix: "+" },
  { value: "24", label: "Support Availability", suffix: "/7" },
];

export const whyPoints = [
  {
    icon: Shield,
    title: "Enterprise-Grade Security",
    desc: "SOC 2 aligned infrastructure with end-to-end encryption, DDoS protection, and comprehensive audit trails for every operation.",
  },
  {
    icon: Globe,
    title: "Global Delivery Team",
    desc: "Our engineering and support teams operate across multiple time zones, ensuring round-the-clock coverage for your business.",
  },
  {
    icon: Cpu,
    title: "Cutting-Edge Technology",
    desc: "Modern cloud-native architecture with AI integration, microservices, and API-first design for maximum flexibility.",
  },
  {
    icon: Briefcase,
    title: "Industry-Specific Expertise",
    desc: "Deep domain knowledge in forex and fintech means our solutions are built for the specific challenges of your industry.",
  },
  {
    icon: Rocket,
    title: "Rapid Deployment",
    desc: "Pre-built, battle-tested modules accelerate your time to market — go from contract to live in as little as 7-14 days.",
  },
  {
    icon: Users,
    title: "Dedicated Account Management",
    desc: "Every client gets a dedicated technical account manager and direct access to our engineering team from day one.",
  },
];

export const techStack = [
  { name: "MetaTrader 4", category: "Trading Platform" },
  { name: "MetaTrader 5", category: "Trading Platform" },
  { name: "cTrader", category: "Trading Platform" },
  { name: "AWS", category: "Cloud" },
  { name: "Google Cloud", category: "Cloud" },
  { name: "Kubernetes", category: "Infrastructure" },
  { name: "PostgreSQL", category: "Database" },
  { name: "Redis", category: "Cache" },
  { name: "React", category: "Frontend" },
  { name: "Node.js", category: "Backend" },
  { name: "Python", category: "AI/ML" },
  { name: "Stripe", category: "Payments" },
];

export const testimonials = [
  {
    name: "James Mitchell",
    role: "CEO, PrimeEdge Brokers",
    company: "PrimeEdge Brokers",
    quote: "CYTAKE delivered our complete broker infrastructure in under 3 weeks. The level of technical expertise and post-launch support has been exceptional. We couldn't have launched without them.",
    avatar: "JM",
    country: "United Kingdom",
  },
  {
    name: "Rahul Sharma",
    role: "CTO, AlphaCapital Prop",
    company: "AlphaCapital Prop",
    quote: "Their prop firm technology is miles ahead of anything else on the market. The challenge engine is rock solid, the trader dashboard is beautiful, and the team responds within hours to any request.",
    avatar: "RS",
    country: "India",
  },
  {
    name: "Ahmad Al-Farsi",
    role: "Managing Director, TradePeak FX",
    company: "TradePeak FX",
    quote: "We migrated our entire CRM and payment infrastructure to CYTAKE. Zero downtime migration, excellent documentation, and the system has been flawless since day one.",
    avatar: "AF",
    country: "UAE",
  },
];
